language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.gradle
before_install:
  - java -version
script:
  - ./gradlew clean
  - ./gradlew test
  - ./gradlew bootRepackage -Pprod -x test
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
